## Sampling Plan

This document constitutes a registration prior to accessing the data. This project will use data obtained by the UK Biobank population-based cohort study [@Sudlow2015]. Participants, aged 40 to 69, completed baseline asssessments in 2006-2010. This involved the collection of biological (e.g. blood) and genetic samples, physical measurements, and an extensive questionnaire focusing on the health and lifestyle of individuals, including occupational factors (e.g. nature of employment). Since 2014, a subset of 100.000 individuals are being invited back for the acquisition of brain, body and heart imaging data. As of May 2020, imaging data for 35,501 volunteers has been made available for research. 

Following approval by the UK Biobank Access Committee (Project ref. no.: 62188), brain imaging data (i.e. task and resting functional brain MRI data) will be obtained for 35,501 participants, together with blood biochemistry assay results (i.e. C-reactive protein) and a curated selection of sociodemographic, lifestyle and health-related information collected through questionnaires, verbal interviews and census data (e.g. Townsend Deprivation Scores). The complete list of data fields requested can be found at http://tiny.cc/UKBBMetaData_62188 (please note, "Participants" attribute refers to total participants in the cohort with information in the selected "Field", not the number of participants in the dataset linked to the current project). Ethical approval for the UK Biobank study was granted by the NHS National Research Ethics Service North West (Ref. no.: 11/NW/0382).